# Generated by Django 4.2.2 on 2023-06-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
