# Generated by Django 4.2.2 on 2023-06-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_alter_order_customer_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
    ]
