# Generated by Django 4.2.2 on 2023-06-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
