# Generated by Django 4.2.2 on 2023-06-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_cart_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='latitude',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='longitude',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='pin_code',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
