# Generated by Django 4.2.2 on 2023-06-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_shippingaddress_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='pin_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
