# Generated by Django 4.2.2 on 2023-07-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_contactmessage_created_extraimage_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
    ]
