# Generated by Django 4.2.2 on 2023-07-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_extraimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraimage',
            name='image',
            field=models.ImageField(upload_to='product/extra_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product/default.png', null=True, upload_to='product/'),
        ),
    ]
